services:
  postgres:
    container_name: library
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: fdiopm1297te7
      POSTGRES_DB: library
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: haci@domain.com
      PGADMIN_DEFAULT_PASSWORD: SecretPassword
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: